---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: sensu-agent
spec:
  minReadySeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sensu-agent
  template:
    metadata:
      labels:
        app: sensu-agent
    spec:
      tolerations: []
      terminationGracePeriodSeconds: 30
      hostPID: true
      hostIPC: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes: []
      containers:
      - name: sensu-agent
        image: sensu/sensu:6.6.3
        command: [
          "/opt/sensu/bin/sensu-agent", "start",
          "--detect-cloud-provider", "true",
          "--log-level", "warn",
        ]
        env:
        - name: KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SENSU_BACKEND_URL
          value: "ws://kube-master:8081"
        - name: SENSU_NAMESPACE
          value: "sensu-system"
        - name: SENSU_SUBSCRIPTIONS
          value: "kubernetes kubernetes/api kubernetes/daemonset"
        - name: SENSU_KEEPALIVE_INTERVAL
          value: "30"
        - name: SENSU_KEEPALIVE_WARNING_TIMEOUT
          value: "120"
        - name: SENSU_DEREGISTER
          value: "true"
        ports: []
        resources:
          limits:
            cpu: 1.0
            memory: 1024M
          requests:
            cpu: 0.25
            memory: 256M
